
title = "Element-wise maximum of 8 bit elements in two vectors"


[dram_pimmax]



[dram_pimmax.v16384_e8__v16384_e8__v16384_e8]
name = "dram_pimmax"
num_operands = 2
operand_sizes = [131072, 131072] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 131072
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE dram_pimmax_v16384_e8(a, b):
   FOR i IN RANGE(0, 131072, 8):
    dst[i+7:i] =  MAX(a[i+7:i],b[i+7:i])
   ENDFOR
"""
