
title = "Vector Addition of vectors"


[pimDiv]

# Vectorization factor 16384


[pimDiv.v16384_e8__v16384_e8__v16384_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [131072, 131072] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 131072
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v16384_e8(a, b):
   FOR i IN RANGE(0, 131072, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v16384_e16__v16384_e16__v16384_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [262144, 262144] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 262144
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v16384_e16(a, b):
   FOR i IN RANGE(0, 262144, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v16384_e32__v16384_e32__v16384_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [524288, 524288] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 524288
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v16384_e32(a, b):
   FOR i IN RANGE(0, 524288 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""




# Vectorization factor  8192


[pimDiv.v8192_e8__v8192_e8__v8192_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [65536, 65536] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 65536
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v8192_e8(a, b):
   FOR i IN RANGE(0, 65536, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v8192_e16__v8192_e16__v8192_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [131072, 131072] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 131072
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v8192_e16(a, b):
   FOR i IN RANGE(0, 131072, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v8192_e32__v8192_e32__v8192_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [262144, 262144] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 262144
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v8192_e32(a, b):
   FOR i IN RANGE(0, 262144 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""


# Vectorization factor  4096


[pimDiv.v4096_e8__v4096_e8__v4096_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [32768, 32768] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 32768
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v4096_e8(a, b):
   FOR i IN RANGE(0, 32768, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v4096_e16__v4096_e16__v4096_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [65536, 65536] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 65536
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v4096_e16(a, b):
   FOR i IN RANGE(0, 65536, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v4096_e32__v4096_e32__v4096_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [131072, 131072] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 131072
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v4096_e32(a, b):
   FOR i IN RANGE(0, 131072 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""


# Vectorization factor  2048


[pimDiv.v2048_e8__v2048_e8__v2048_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [16384, 16384] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 16384
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v2048_e8(a, b):
   FOR i IN RANGE(0, 16384, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v2048_e16__v2048_e16__v2048_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [32768, 32768] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 32768
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v2048_e16(a, b):
   FOR i IN RANGE(0, 32768, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v2048_e32__v2048_e32__v2048_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [65536, 65536] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 65536
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v2048_e32(a, b):
   FOR i IN RANGE(0, 65536 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""



# Vectorization factor  1024


[pimDiv.v1024_e8__v1024_e8__v1024_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [8192, 8192] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 8192
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v1024_e8(a, b):
   FOR i IN RANGE(0, 8192, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v1024_e16__v1024_e16__v1024_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [16384, 16384] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 16384
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v1024_e16(a, b):
   FOR i IN RANGE(0, 16384, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v1024_e32__v1024_e32__v1024_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [32768, 32768] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 32768
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v1024_e32(a, b):
   FOR i IN RANGE(0, 32768 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""



# Vectorization factor  512


[pimDiv.v512_e8__v512_e8__v512_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [4096, 4096] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 4096
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v512_e8(a, b):
   FOR i IN RANGE(0, 4096, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v512_e16__v512_e16__v512_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [8192, 8192] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 8192
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v512_e16(a, b):
   FOR i IN RANGE(0, 8192, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v512_e32__v512_e32__v512_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [16384, 16384] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 16384
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v512_e32(a, b):
   FOR i IN RANGE(0, 16384 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""




# Vectorization factor  256


[pimDiv.v256_e8__v256_e8__v256_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [2048, 2048] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 2048
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v256_e8(a, b):
   FOR i IN RANGE(0, 2048, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v256_e16__v256_e16__v256_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [4096, 4096] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 4096
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v256_e16(a, b):
   FOR i IN RANGE(0, 4096, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v256_e32__v256_e32__v256_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [8192, 8192] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 8192
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v256_e32(a, b):
   FOR i IN RANGE(0, 8192 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""




# Vectorization factor  128


[pimDiv.v128_e8__v128_e8__v128_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [1024, 1024] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 1024
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v128_e8(a, b):
   FOR i IN RANGE(0, 1024, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v128_e16__v128_e16__v128_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [2048, 2048] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 2048
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v128_e16(a, b):
   FOR i IN RANGE(0, 2048, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v128_e32__v128_e32__v128_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [4096, 4096] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 4096
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v128_e32(a, b):
   FOR i IN RANGE(0, 4096 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""



# Vectorization factor  64


[pimDiv.v64_e8__v64_e8__v64_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [512, 512] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 512
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v64_e8(a, b):
   FOR i IN RANGE(0, 512, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v64_e16__v64_e16__v64_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [1024, 1024] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size = 1024 
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v64_e16(a, b):
   FOR i IN RANGE(0, 1024, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v64_e32__v64_e32__v64_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [2048, 2048] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 2048
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v64_e32(a, b):
   FOR i IN RANGE(0, 2048 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""



# Vectorization factor  32


[pimDiv.v32_e8__v32_e8__v32_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [256, 256] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 256
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v32_e8(a, b):
   FOR i IN RANGE(0, 256, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v32_e16__v32_e16__v32_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [512, 512] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size =  512
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v32_e16(a, b):
   FOR i IN RANGE(0, 512, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v32_e32__v32_e32__v32_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [1024, 1024] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 1024
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v32_e32(a, b):
   FOR i IN RANGE(0, 1024 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""



# Vectorization factor  16


[pimDiv.v16_e8__v16_e8__v16_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [128, 128] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 128
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v16_e8(a, b):
   FOR i IN RANGE(0, 128, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v16_e16__v16_e16__v16_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [256, 256] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size =  256
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v16_e16(a, b):
   FOR i IN RANGE(0, 256, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v16_e32__v16_e32__v16_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [512, 512] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 512
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v16_e32(a, b):
   FOR i IN RANGE(0, 512 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""


# Vectorization factor  8


[pimDiv.v8_e8__v8_e8__v8_e8]
name = "pimDiv"
num_operands = 2
operand_sizes = [64, 64] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [8, 8]
result_layout = "DRAM_VERT"
result_size = 64
result_elem_bw = 8
signedness = 1
semantics = """\
DEFINE pimDiv_v8_e8(a, b):
   FOR i IN RANGE(0, 64, 8):
    dst[i+7:i] = a[i+7:i] / b[i+7:i] 
   ENDFOR
"""


[pimDiv.v8_e16__v8_e16__v8_e16]
name = "pimDiv"
num_operands = 2
operand_sizes = [128, 128] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [16, 16]
result_layout = "DRAM_VERT"
result_size =  128
result_elem_bw = 16
signedness = 1
semantics = """\
DEFINE pimDiv_v8_e16(a, b):
   FOR i IN RANGE(0, 128, 16):
    dst[i+15:i] = a[i+15:i] / b[i+15:i] 
   ENDFOR
"""

[pimDiv.v8_e32__v8_e32__v8_e32]
name = "pimDiv"
num_operands = 2
operand_sizes = [256, 256] # Number of bits for each operand
operand_layouts = ["DRAM_VERT", "DRAM_VERT"] 
operand_elem_bw = [32, 32]
result_layout = "DRAM_VERT"
result_size = 256
result_elem_bw = 32
signedness = 1
semantics = """\
DEFINE pimDiv_v8_e32(a, b):
   FOR i IN RANGE(0, 256 , 32):
    dst[i+31:i] = a[i+31:i] / b[i+31:i] 
   ENDFOR
"""
